name: "Ubuntu 20.04 Image"

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'Ubuntu-20.04/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'Ubuntu-20.04/**'

jobs:
  Build_Image:
    uses: ./.github/workflows/build-image.yaml
    with:
      name: 'Ubuntu-20.04'
